# -*- coding: utf-8 -*-
"""Eigen Val,Vec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kj0kYv0yjG1THHVsjrNRGzKlWkOMBOya
"""

from numpy import *
import scipy.linalg as la
A=matrix([[1,2],[3,4]])
print(A)
eigvals, eigvecs=la.eig(A)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)

B=matrix([[2,27,0],[0,4,40],[0,3,30]])
print(B)
eigvals, eigvecs = la.eig(B)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)

A=matrix([[1,1,1],[1,1,1],[1,1,1]])
print(A)
eigvals, eigvecs = la.eig(A)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)
P=eigvecs
print(P)
D=zeros((3,3))
for i in range(3):
  D[i,i]=eigvals[i]
  print(D)
P_inv=la.inv(P)
print(P_inv)
print(P@D@P_inv)

A=matrix([[1,1,1],[0,1,1],[0,0,1]])
print(A)
eigvals, eigvecs = la.eig(A)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)
P=eigvecs
print(P)
D=zeros((3,3))
for i in range(3):
  D[i,i]=eigvals[i]
  print(D)
P_inv=la.inv(P)
print(P_inv)
print(P@D@P_inv)

A=matrix([[0,-6,-4],[5,-11,-6],[-6,9,4]])
print(A)
eigvals, eigvecs = la.eig(A)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)
P=eigvecs
print(P)
D=zeros((3,3))
for i in range(3):
  D[i,i]=eigvals[i]
  print(D)
P_inv=la.inv(P)
print(P_inv)
print(P@D@P_inv)

A=matrix([[0,1,0],[0,0,1],[-2,1,2]])
print(A)
eigvals, eigvecs = la.eig(A)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)
P=eigvecs
print(P)
D=zeros((3,3))
for i in range(3):
  D[i,i]=eigvals[i]
  print(D)
P_inv=la.inv(P)
print(P_inv)
print(P@D@P_inv)

from numpy import *
import scipy.linalg as la
A=matrix([[1,2],[3,4]])
print(A)
eigvals, eigvecs = la.eig(A)
print('eigen values=',eigvals)
print('eigen vectors=',eigvecs)
P=eigvecs
print(P)
D=zeros((2,2))
for i in range(2):
  D[i,i]=eigvals[i]
  print(D)
P_inv=la.inv(P)
print(P_inv)
print(P@D@P_inv)